### ISSUE TITLE
project maintainer

### ISSUE THREAD

**Issue by ashwin31** [guybowden/django-forex#1]
Hi @guybowden we are starting to do django-forex app. Can you transfer yours, so that we can develop it further.

**Comment by guybowden** [comment]
Hi Ashwin - what are you planning to do with it?

**Comment by guybowden** [comment]
FYI - I just updated the repo with the latest work that has been used in production at muchbetteradventures.com for the past few years

**Comment by ashwin31** [comment]
Oh, I thought its discontinued and saw I could use it to develop django-forex app for giving the ability for developers to make it easy of currency conversions. https://github.com/MicroPyramid/django-forex we already started the repo and stopped because of naming conflict.

**Comment by ashwin31** [comment]
is https://pypi.python.org/pypi/django_forex not yours?

**Comment by guybowden** [comment]
Nope - that's not mine - that seems to be less useful than this one. With the latest commit, this one is pretty useful for our needs. It syncs with openexchangerates.org via the management command, keeps a history of rates for future use and allows you to do simple conversions. Could do with a bit more of a readme, and perhaps a tidy up here and there, but it works for us and has done for about 4 years. (plus putting onto pypi)

**Comment by ashwin31** [comment]
Okay Thank you @guybowden have a good day.
